import type { Metadata } from "next";
import SiteHeader from "@/components/Site/Header";
import { Toaster } from "@/components/ui/sonner";
import Auth from "@/components/Auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SiteLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <SiteHeader />
      <Auth />
      <div>{children}</div>
      <Toaster position="top-center" offset={"2rem"} theme="system" />
    </>
  );
}
